[package]
name = "factorio-bp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "factorio-bp-analyzer"
path = "src/main.rs"
