[package]
name = "factorio_bp_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[features]
default = []

[lib]
crate-type = ["rlib"]
edition = "2021"
